name: A workflow for my Hello World file # gives a name to workflow. This name appears on any pull request or in the Actions tab, especially useful when there are multiple workflows in your repository.
on: push #  indicates that the workflows will execute anytime code is pushed to repository.

jobs: # is the base component of a workflow run
  build: # is the identifier we're attaching to this job
    name: Hello world action # is the name of the job, this is displayed on GitHub when the workflow is running
    runs-on: ubuntu-latest # defines the type of machine to run the job on. The machine can be either a GitHub-hosted runner or a self-hosted runner.
    steps: # the linear sequence of operations that make up a job
      - uses: actions/checkout@v1 # uses a community action called checkout to allow the workflow to access the contents of the repository
      - uses: ./action-a # provides the relative path to the action we created in the action-a directory of the repository
        with: # is used to specify the input variables that will be available to your action in the runtime environment. 
          MY_NAME: "Ana" # In this case, the input variable is MY_NAME, and it is currently initialized to "Mona".